### ISSUE TITLE
[1.10.2] Texture Compatibility with Soartex Fanver

### ISSUE THREAD

**Issue by MokahTGS** [tobystrong/CompactStorage#47]
With the newest update it seems the storage builder block has lost it's compatibility with the Soartex Fanver texture pack.

https://www.dropbox.com/s/udppzkagb16snjw/2017-05-06_10.39.06.png?dl=0

Not sure what you can do but thought I'd mention it.  Is there something I can do on my end?

**Comment by tobystrong** [comment]
watttt

**Comment by tobystrong** [comment]
Ok.

So when I was updating from 1.9 to 1.11 I noticed that capitalisation in block models was ignored, so I changed everything to lower-case just to get into the habit and to keep everything the same (so chestbuilder.json not chestBuilder.json). I assume in Soartex there is a texture for the builder and if so it's probably broken because it's chestBuilder not chestbuilder. If not let me know and I'll look into it further but that's most likely the reason as I didn't reupdate from 1.9 to 1.10 I backdated the 1.11 version so those changes remained. Should've mentioned it in patch notes I guess  ¯\_(ツ)_/¯
